#!/bin/bash

#   FAJL="";cd ~/;rm -f $FAJL.sh;wget https://raw.githubusercontent.com/BLBMS/am-t/moje/0/q/$FAJL.sh;chmod +x $FAJL.sh;./$FAJL.sh

# in termux

ime_iz_ww=$(basename ~/*.ww)
delavec=${ime_iz_ww%.ww}
echo -e "\e[0m  WORKER:\e[96m $delavec\e[0m"

pkg update
pkg upgrade -y
pkg install proot-distro -y
proot-distro install ubuntu
proot-distro login ubuntu

# in ubuntu

cd ~/
#rm -f *.ww
#echo $delavec > ~/$delavec.ww
cat /etc/os-release
sleep 2
apt update
apt upgrade -y
apt install wget -y
wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v0.4.1/rqiner-aarch64-mobile
chmod u+x rqiner-aarch64-mobile
rm -f config.sh
wget https://raw.githubusercontent.com/BLBMS/am-t/moje/0/q/config.sh
chmod +x config.sh
sed -i "s#DELAVEC#$delavec#g" config.sh


echo " "  >> ~/.bashrc
echo "###    MOJE"  >> ~/.bashrc
# zbriše vse za MOJE
awk '!f; /MOJE/ {f=1}' ~/.bashrc > ~/.bashrc.tmp && mv ~/.bashrc.tmp ~/.bashrc

#echo "###    MOJE"  >> ~/.bashrc

cat << EOF >> ~/.bashrc
alias ss='~/qstart.sh'
alias xx='screen -ls | grep -o "[0-9]\+\." | awk "{print }" | xargs -I {} screen -X -S {} quit && screen -ls'
alias sl='screen -ls | sed -E "s/RQiner/\x1b[32m&\x1b[0m/g" | tail -n +2 | head -n -1'
alias sll='screen -ls'
alias rr='screen -r RQiner'
EOF
