#!/bin/bash

# in termux

ime_iz_ww=$(basename ~/*.ww)
delavec=${ime_iz_ww%.ww}
echo -e "\e[0m  WORKER:\e[96m $delavec\e[0m"

pkg update
pkg upgrade -y
pkg install proot-distro -y
proot-distro install ubuntu
proot-distro login ubuntu

# in ubuntu

cat /etc/os-release
apt update
apt upgrade -y
apt install wget -y
wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v0.4.1/rqiner-aarch64-mobile
chmod u+x rqiner-aarch64-mobile
cat << EOF > ~/qs
./rqiner-aarch64-mobile -t8 -i NFCEVVPMJVQAFBRWIWQJTIICADPAUTJSCGNYWGBOCFWPPSBSCZQRGVQGLKHI -l DELAVEC
EOF
chmod +x qs
echo "###    MOJE"  >> ~/.bashrc
echo "alias qs='~/qs'"  >> ~/.bashrc
