#!/bin/bash

cat /etc/os-release
apt update
apt upgrade -y
apt install wget
wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v0.4.1/rqiner-aarch64-mobile
chmod u+x rqiner-aarch64-mobile
./rqiner-aarch64-mobile -t8 -i NFCEVVPMJVQAFBRWIWQJTIICADPAUTJSCGNYWGBOCFWPPSBSCZQRGVQGLKHI -l S9a
