# Check if qnohup.sh is already running
if ! pgrep -f "rqiner-aarch64" > /dev/null; then
    bash "$HOME/qnohup.sh"
else
    echo "qnohup.sh is already running"
fi

# Run third.sh to monitor log and control third_miner.sh
if ! pgrep -f "third.sh" > /dev/null; then
    nohup bash "$HOME/third.sh" > /dev/null 2>&1 &
fi
