#!/bin/bash
LIST=""
while read line; do
    ip=$(echo "$line" | awk '{print $1}')
    LIST+="192.168.100.$ip "
done < spisek.list
LIST=$(echo "$LIST" | sed 's/ *$//')
SCRIPTPATH=$(dirname $(realpath $0))
BUILD="["
act=0
inact=0
khsall=0
for i in $LIST; do
 ii=$(echo "$i" | rev | cut -d '.' -f 1 | rev)
 device=$(grep -w "$ii" spisek.list | cut -f 2 | rev | cut -d ' ' -f 1 | rev)
 RESPONSE=$(printf "{\"PHONE\":\"$device\",\"HOST\":\"$i\",\""; $SCRIPTPATH/api.pl -c summary -a $i -p 4068 | tr -d '\0' | sed -r \
  's/=/":"/g; s/;/\",\"/g' | sed 's/|/",/g')$(printf "\""; $SCRIPTPATH/api.pl -c pool -a $i -p 4068 | tr -d \
  '\0' | sed -r 's/=/":"/g' | sed -r 's/;/\",\"/g' | sed 's/|/"},/g')
 if [[ "$RESPONSE" == *"No Connect"* ]]; then
  inact=$((inact+1))
  BUILD=$BUILD"{\"PHONE\":\"$device\",\"HOST\":\"$i\"},"
 else
  BUILD=$BUILD$RESPONSE
  RESP=$(echo "$RESPONSE" | sed 's/,$//')
  act=$((act+1))
  khs1=$(echo "$RESP" | jq -r '.KHS' | awk -F. '{print $1}')
  khsall=$((khsall + khs1))
 fi
done
mhsall=$(bc <<< "scale=3; $khsall / 1000")
BUILD=$BUILD"{\"PHONE\":\"ALL\",\"HOST\":\"PHONES=\",\"POOL\":\"$mhsall\",\"KHS\":\"MHs\"},"
BUILD=$BUILD"{\"PHONE\":\"active=\",\"HOST\":\"$act\",\"POOL\":\"inactive=\",\"KHS\":\"$inact\"},"
JSON=$(echo $BUILD | tr -d '\r\n' | sed "s/.\{0,2\}$//; /^$/d"; printf "}]")
echo $JSON | jq '[.[] | {PHONE,HOST,POOL,USER,KHS,DIFF,ACC,REJ,WAIT,UPTIME,TS,POOL}]'
